version: '3.7'

services:

  django:
    build: ./backend
    ports:
      - 8000:8000 # Expose Backend API Port
      - 3000:3000
      - 35729:35729
      - 5678:5678 # Expose Port for ptvsd debugger (https://testdriven.io/blog/django-debugging-vs-code/)
    volumes:
      - ./backend:/app
    # env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    tty: true # Colorised Terminal Output

    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nataliafilipkiewicz
      - POSTGRES_PASSWORD=natalka
      - POSTGRES_DB=nataliafilipkiewicz

    ports:
      - "5432:5432"
    
volumes:
  postgres_data: